[[station]]
name = "100hitz - 90's Alternative [128k] · United States Of America"
url = "http://pureplay.cdnstream1.com/6040_128.mp3?DIST=TuneIn&TGT=TuneIn&maxServers=2&gdpr=0&us_privacy=1YNY&partnertok=eyJhbGciOiJIUzI1NiIsImtpZCI6InR1bmVpb"

[[station]]
name = "Radio FM"
url = "https://icecast.stv.livebox.sk/fm_128.mp3"

[[station]]
name = "KEXP [162k] · United States Of America"
url = "https://kexp.streamguys1.com/kexp160.aac?listenerid=f4bcb5c771d830fbdd4195088a946ea6&awparams=companionAds%3Atrue"
