# Enable mouse support
set -g mouse on

# Use 256 colors
set -g default-terminal "tmux-256color"

# Increase history scrollback
set -g history-limit 10000

# Improve status bar readability
#set -g status-bg black
#set -g status-fg white

# Reload tmux config with prefix + r
bind r source-file ~/.tmux.conf \; display "Config Reloaded."

# Split panes more conveniently
bind | split-window -h  # Vertical split
bind - split-window -v  # Horizontal split

# Switch panes with Alt + arrow keys
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Vim-style pane navigation
setw -g mode-keys vi

# Start counting pane and window number at 1
set -g base-index 1
setw -g pane-base-index 1

#set -g pane-border-status top
#set -g pane-border-format "#{pane_title}"

# Initialize TPM
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'jaclu/tmux-power-zoom'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'



